os: Visual Studio 2015 CTP  
version: 1.1.0.{build}

configuration:
- Debug
- Release

environment:
  matrix:
  # - VS_VERSION: 9 2008
  #   VS_PLATFORM: win32
  # - VS_VERSION: 9 2008
  #   VS_PLATFORM: x64
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: win32
  #- VS_VERSION: 10 2010
  #  VS_PLATFORM: x64
   - VS_VERSION: 11 2012
     VS_PLATFORM: win32
   - VS_VERSION: 11 2012
     VS_PLATFORM: x64
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: win32
  #- VS_VERSION: 12 2013
  #  VS_PLATFORM: x64
   - VS_VERSION: 14 2015
     VS_PLATFORM: win32
   - VS_VERSION: 14 2015
     VS_PLATFORM: x64
  # - VS_VERSION: 15 2017
  #   VS_PLATFORM: win32
  # - VS_VERSION: 15 2017
  #   VS_PLATFORM: x64
before_build:
- git submodule update --init --recursive
- cmake -H. -Bbuild/vs -G "Visual Studio %VS_VERSION%" -DCMAKE_GENERATOR_PLATFORM=%VS_PLATFORM%

build:
  project: build\vs\%APPVEYOR_PROJECT_NAME%.sln
  parallel: true
  verbosity: minimal

test_script:
# Environment variables https://www.appveyor.com/docs/environment-variables/
- echo %APPVEYOR_REPO_NAME%
- echo %APPVEYOR_PROJECT_NAME%
- echo %APPVEYOR_ACCOUNT_NAME%

